language: ruby
rvm:
  - 2.7.2

services:
  - docker

before_install:
  - gem install bundler -v 2.1.4
  - docker pull eclipse-mosquitto
  - docker run -it -d -p 1883:2883 -p 9001:9001 eclipse-mosquitto

env:
  - REMOTE_MOSQUITTO=true

script:
  - bundle exec rspec
